/**
 * Auto-generated Team IDs
 * Generated at: 2026-01-03T16:39:03.182Z
 * Total Teams: 352
 */

export type TeamId = number;

export interface TeamInfo {
  id: TeamId;
  slug: string;
  name: string;
  league: 'VSL' | '1LIG' | '2LIG' | 'CEV_CL' | 'CEV_CUP' | 'CEV_CHALLENGE';
  country: string | null;
  groupName: string | null;
  clubId?: string | null;
}

export const TEAM_IDS: Record<string, TeamId> = {
  'aras-kargo-vsl': 1000,
  'aydin-buyuksehi-r-beledi-yespor-vsl': 1001,
  'bahceli-evler-bld-vsl': 1002,
  'besi-ktas-vsl': 1003,
  'eczacibasi-dynavi-t-vsl': 1004,
  'fenerbahce-medicana-vsl': 1005,
  'galatasaray-daikin-vsl': 1006,
  'goztepe-vsl': 1007,
  'i-lbank-vsl': 1013,
  'kuzeyboru-vsl': 1008,
  'ni-lufer-beledi-yespor-eker-vsl': 1009,
  'turk-hava-yollari-vsl': 1010,
  'vakifbank-vsl': 1011,
  'zeren-spor-vsl': 1012,
  'afyon-bld-yuntas-1lig': 1033,
  'alfemo-zeren-spor-1lig': 1030,
  'altinordu-1lig': 1021,
  'bodrum-bld-bodrumspor-1lig': 1024,
  'canakkale-bld-1lig': 1015,
  'deni-zli-b-sehi-r-bld-1lig': 1017,
  'di-yarbakir-b-sehi-r-bld-1lig': 1029,
  'eczacibasi-1lig': 1016,
  'endo-karsiyaka-1lig': 1022,
  'fdm-yapi-konya-eregli-bld-1lig': 1038,
  'fenerbahce-medicana-1lig': 1014,
  'havran-bld-1lig': 1025,
  'i-ba-ki-mya-ted-ankara-kolejli-ler-1lig': 1039,
  'i-bb-spor-kulubu-1lig': 1018,
  'i-lbank-1lig': 1028,
  'karayollari-1lig': 1032,
  'kuzeyboru-maxi-pi-pe-spor-1lig': 1026,
  'meri-nos-voleybol-1lig': 1031,
  'muratpasa-bld-aci-koleji-1lig': 1036,
  'ptt-1lig': 1037,
  'sakarya-voleybol-1lig': 1027,
  'si-gorta-shop-mke-ankaragucu-1lig': 1035,
  'trendy-hotels-manavgat-bld-1lig': 1034,
  'vakifbank-1lig': 1019,
  'vestel-mani-sa-b-sehi-r-bld-1lig': 1023,
  'yesi-lyurt-1lig': 1020,
  '07-mega-spor-2lig': 1122,
  '52-camlik-spor-2lig': 1198,
  '73-sirnak-bld-2lig': 1216,
  '91000-dev-spor-2lig': 1212,
  'aci-koleji-2lig': 1120,
  'adana-b-sehi-r-bld-2lig': 1185,
  'adana-sporcu-egi-ti-m-spor-2lig': 1183,
  'adana-t-d-s-2lig': 1180,
  'afyon-gencli-k-spor-2lig': 1129,
  'ahmet-hamdi-tanpinar-ortaokulu-2lig': 1160,
  'akdeni-z-bi-lgi-spor-2lig': 1123,
  'akhi-sar-bld-2lig': 1098,
  'akhi-sar-gucu-2lig': 1097,
  'al-ka-altin-kanatlar-2lig': 1142,
  'alp-spor-2lig': 1080,
  'altay-2lig': 1093,
  'altinay-spor-2lig': 1099,
  'altinyurt-2lig': 1062,
  'ankara-barosu-2lig': 1157,
  'ankara-dsi-2lig': 1168,
  'antepi-a-2lig': 1208,
  'arkas-spor-2lig': 1107,
  'arnavutkoy-bld-2lig': 1047,
  'arsavev-hatay-voleybol-2lig': 1187,
  'ata-okul-spor-2lig': 1096,
  'atasehi-r-kartallari-2lig': 1071,
  'avrupa-voleybol-geli-si-m-2lig': 1040,
  'aydin-buyuksehi-r-beledi-yespor-2lig': 1111,
  'b-sehi-r-bld-ankara-spor-2lig': 1176,
  'bahceli-evler-bld-2lig': 1052,
  'bahcesehi-r-koleji-dalaman-bld-2lig': 1131,
  'balikesi-r-b-sehi-r-bld-2lig': 1082,
  'balikesi-r-dsi-2lig': 1090,
  'bandirma-celi-k-spor-2lig': 1083,
  'bartin-volley-academy-2lig': 1149,
  'basaksehi-r-voleybol-2lig': 1054,
  'baskent-ada-spor-2lig': 1155,
  'baskent-zi-rve-2lig': 1170,
  'bayburt-gencli-k-merkezi-2lig': 1190,
  'bayrakli-bld-2lig': 1102,
  'bergama-bld-2lig': 1104,
  'besi-kduzu-2lig': 1199,
  'besi-ktas-naviosa-2lig': 1055,
  'beyli-kduzu-beykent-2lig': 1042,
  'bi-zi-mkent-voleybol-2lig': 1044,
  'bolu-ataturk-anadolu-li-sesi-2lig': 1154,
  'bursa-b-sehi-r-bld-2lig': 1136,
  'bursa-fethi-ye-1973-spor-2lig': 1134,
  'buyuk-resi-tpasa-ortaokulu-2lig': 1056,
  'buyukcekmece-voleybol-akademi-2lig': 1050,
  'cadence-boya-golcuk-i-hsani-ye-2lig': 1146,
  'can-mi-lan-atleti-k-2lig': 1064,
  'caba-spor-2lig': 1173,
  'can-kale-spor-2lig': 1087,
  'canakkale-kepez-2lig': 1085,
  'catalca-bld-2lig': 1041,
  'cekmekoy-i-stanbul-spor-2lig': 1077,
  'cengelkoy-voleybol-2lig': 1066,
  'cerkezkoy-voleybol-akademi-2lig': 1086,
  'corlu-bld-2lig': 1092,
  'corum-arena-spor-2lig': 1194,
  'corum-voleybol-2lig': 1201,
  'deni-zli-b-sehi-r-bld-2lig': 1125,
  'dev-atasehi-r-2lig': 1068,
  'di-yarbakir-voleybolcular-2lig': 1211,
  'dogu-akademi-2lig': 1069,
  'duzce-voleybol-2lig': 1144,
  'efor-gencli-k-2lig': 1095,
  'elazig-bld-2lig': 1220,
  'eli-t-akdeni-z-2lig': 1121,
  'endo-karsiyaka-2lig': 1118,
  'english-time-spor-2lig': 1164,
  'eregli-sumer-spor-2lig': 1179,
  'eryaman-geli-si-m-2lig': 1167,
  'eski-sehi-r-peyman-spor-2lig': 1135,
  'eski-sehi-r-sehi-r-koleji-egt-kultur-2lig': 1143,
  'eti-mesgut-bld-geli-si-m-2lig': 1165,
  'eyupsultan-bld-2lig': 1061,
  'fenerbahce-medicana-2lig': 1072,
  'fethi-ye-voleybol-2lig': 1126,
  'firat-ozkan-2lig': 1206,
  'forza-spor-2lig': 1106,
  'galatasaray-2lig': 1070,
  'gazi-antep-bld-2lig': 1210,
  'gazi-emi-r-bld-2lig': 1115,
  'gebze-gencli-k-ve-spor-2lig': 1147,
  'geli-si-m-koleji-2lig': 1108,
  'gemli-k-i-sti-klal-spor-2lig': 1133,
  'golbasi-i-ncek-spor-2lig': 1159,
  'goztepe-2lig': 1101,
  'gungoren-voleybol-2lig': 1053,
  'gural-premier-antalyaspor-2lig': 1127,
  'hakan-akisik-spor-2lig': 1163,
  'hakkari-maemtal-2lig': 1217,
  'hakkari-sporti-f-faali-yetler-2lig': 1219,
  'harput-lahmacun-yahya-kaptan-2lig': 1148,
  'hedef-ankara-2lig': 1178,
  'heki-moglu-global-connect-travel-bvi-2lig': 1132,
  'hoca-ahmet-yesevi-anadolu-l-es-voleybol--2lig': 1137,
  'hopa-beledi-ye-2lig': 1192,
  'isparta-gencli-k-spor-2lig': 1124,
  'i-lbank-2lig': 1158,
  'i-stanbul-bi-zi-mkent-spor-2lig': 1046,
  'i-zmi-r-b-sehir-bld-2lig': 1114,
  'i-zmi-r-dsi-2lig': 1116,
  'i-zmi-t-spor-2lig': 1151,
  'kamari-n-spor-2lig': 1074,
  'karabuk-gencli-k-spor-2lig': 1145,
  'kartal-anadolu-2lig': 1078,
  'kartal-bld-2lig': 1079,
  'kavak-spor-2lig': 1169,
  'kayseri-ci-mnasti-k-spor-2lig': 1203,
  'kayseri-voleybol-2lig': 1204,
  'kirklareli-gencli-k-spor-2lig': 1089,
  'kocaeli-ni-comedi-a-akademi-2lig': 1150,
  'kocaeli-voleybol-akademi-2lig': 1153,
  'kuzey-yildizlari-2lig': 1081,
  'kucukcekmece-voleybol-2lig': 1048,
  'kzy-spor-2lig': 1103,
  'lanueva-kozmeti-k-anadolu-marmara-2lig': 1065,
  'mac-sayisi-2lig': 1067,
  'malatya-voleybol-2lig': 1214,
  'margenc-2lig': 1213,
  'marmari-s-bld-2lig': 1130,
  'media-first-ayvalik-geli-si-m-spor-2lig': 1084,
  'mehmet-ege-i-nsaat-i-negol-orhani-ye-vol-2lig': 1140,
  'mehmet-erdem-marmara-akademi-2lig': 1075,
  'meri-nos-voleybol-2lig': 1205,
  'mg-spor-2lig': 1138,
  'misiroglu-beytepe-2lig': 1174,
  'mke-ankaragucu-2lig': 1172,
  'mus-oli-mpi-k-spor-2lig': 1215,
  'ni-cer-hotel-voleybol-2lig': 1218,
  'ni-lufer-bld-2lig': 1139,
  'okura-loji-sti-k-mersi-n-i-hti-sas-2lig': 1184,
  'osmancik-bld-2lig': 1196,
  'polat-group-di-di-m-beledi-yespor-2lig': 1109,
  'polatli-duatepe-2lig': 1177,
  'ptt-2lig': 1166,
  'ri-ze-endustri-meslek-li-sesi-2lig': 1200,
  'roberteam-2lig': 1058,
  'rota-koleji-2lig': 1112,
  'semt-asansor-bordo-mavi-61-2lig': 1197,
  'serdi-van-bld-2lig': 1152,
  'seyhan-bld-2lig': 1182,
  'sinav-koleji-samsunspor-2lig': 1191,
  'si-banet-kozan-i-mamoglu-spor-2lig': 1189,
  'si-li-vri-cagribey-2lig': 1049,
  'si-lopi-bld-sporti-f-faali-yetler-2lig': 1222,
  'si-lopi-geli-si-m-faali-yetleri-2lig': 1221,
  'si-vas-toprak-gayri-menkul-pars-akademi-2lig': 1209,
  'smac-spor-2lig': 1045,
  'smart-holding-a-s-cayeli-2lig': 1195,
  'soke-beledi-ye-saldos-voleybol-2lig': 1113,
  'superpool-findikli-1974-2lig': 1193,
  'tarsus-ameri-kan-koleji-2lig': 1181,
  'ted-ankara-kolejli-ler-2lig': 1175,
  'tek-metal-sporti-f-2lig': 1161,
  'teki-rdag-voleybol-i-hti-sas-2lig': 1091,
  'temi-z-enerji-birli-gi-2lig': 1156,
  'toros-universi-tesi-volgem-2lig': 1188,
  'toroslar-bld-2lig': 1186,
  'toyzz-shop-di-namo-spor-2lig': 1073,
  'turgutlu-bld-kultur-sanat-2lig': 1105,
  'tuzla-mercan-2lig': 1076,
  'turk-hava-yollari-2lig': 1043,
  'turkoglu-spor-kulubu-2lig': 1094,
  'tvf-spor-li-sesi-2lig': 1162,
  'uysallar-oto-fethi-ye-zi-rve-2lig': 1128,
  'ulku-spor-2lig': 1110,
  'unsped-2lig': 1051,
  'vefa-2lig': 1060,
  'venus-spor-2lig': 1117,
  'vi-ransehi-r-voleybol-2lig': 1207,
  'volkan-guc-spor-2lig': 1119,
  'world-medicine-ates-spor-2lig': 1063,
  'yalova-ci-ftli-kkoy-bld-2lig': 1141,
  'yedi-dag-spor-2lig': 1171,
  'yeni-ay-loji-sti-k-sariyer-konak-spor-2lig': 1057,
  'yesi-l-bayrami-c-2lig': 1088,
  'yesi-lyurt-2lig': 1059,
  'yunusemre-bld-2lig': 1100,
  'zeugma-gazi-antep-spor-2lig': 1202,
  'a-carraro-prosecco-doc-conegliano-cev-cl': 1235,
  'ankara-zeren-spor-kulubu-cev-cl': 1236,
  'cs-volei-alba-blaj-cev-cl': 1225,
  'dresdner-sc-cev-cl': 1237,
  'eczacibasi-istanbul-cev-cl': 1232,
  'fenerbahce-medicana-istanbul-cev-cl': 1227,
  'igor-gorgonzola-novara-cev-cl': 1228,
  'ks-developres-rzesz-w-cev-cl': 1240,
  'levallois-paris-saint-cloud-cev-cl': 1241,
  'ks-commercecon-d-cev-cl': 1238,
  'maritza-plovdiv-cev-cl': 1242,
  'numia-vero-volley-milano-cev-cl': 1231,
  'ok-elezni-ar-lajkovac-cev-cl': 1234,
  'olympiacos-piraeus-cev-cl': 1233,
  'pge-budowlani-d-cev-cl': 1230,
  'savino-del-bene-scandicci-cev-cl': 1223,
  'sport-lisboa-e-benfica-cev-cl': 1229,
  'ssc-palmberg-schwerin-cev-cl': 1239,
  'vakifbank-istanbul-cev-cl': 1224,
  'volero-le-cannet-cev-cl': 1226,
  'ac-paok-thessaloniki-cev-cup': 1266,
  'allianz-mtv-stuttgart-cev-cup': 1245,
  'asterix-avo-beveren-cev-cup': 1260,
  'avarca-de-menorca-cev-cup': 1268,
  'bks-bostik-bielsko-bia-a-cev-cup': 1252,
  'c-s-o-voluntari-2005-cev-cup': 1247,
  'cd-heidelberg-las-palmas-cev-cup': 1267,
  'darta-bevo-roeselare-cev-cup': 1259,
  'dinamo-bucuresti-cev-cup': 1248,
  'dukla-liberec-cev-cup': 1265,
  'fc-porto-cev-cup': 1261,
  'galatasaray-daikin-istanbul-cev-cup': 1243,
  'janta-volej-kisela-voda-cev-cup': 1273,
  'mbh-b-k-scsaba-cev-cup': 1255,
  'mladost-zagreb-cev-cup': 1257,
  'moya-radomka-radom-cev-cup': 1253,
  'ok-dinamo-zagreb-cev-cup': 1258,
  'otp-banka-branik-maribor-cev-cup': 1254,
  'reale-mutua-fenera-chieri-76-cev-cup': 1249,
  'sporting-cp-lisboa-cev-cup': 1262,
  'tent-obrenovac-cev-cup': 1269,
  'thy-istanbul-cev-cup': 1244,
  'vandoeuvre-nancy-vb-cev-cup': 1251,
  'vasas-buda-budapest-cev-cup': 1256,
  'vfb-suhl-thuringen-cev-cup': 1246,
  'viteos-neuchatel-uc-cev-cup': 1263,
  'vk-up-olomouc-cev-cup': 1264,
  'volley-mulhouse-alsace-cev-cup': 1250,
  'ok-gacko-rd-swisslion-cev-cup': 1272,
  'ok-ribola-ka-tela-cev-cup': 1271,
  'zok-ub-cev-cup': 1270,
  'aek-athens-cev-challenge': 1274,
  'aek-athens-gre-cev-challenge': 1318,
  'ao-thiras-cev-challenge': 1294,
  'ao-thiras-gre-cev-challenge': 1338,
  'buducnost-podgorica-cev-challenge': 1301,
  'buducnost-podgorica-mne-cev-challenge': 1345,
  'c-s-m-lugoj-cev-challenge': 1287,
  'c-s-m-lugoj-rou-cev-challenge': 1331,
  'draisma-dynamo-apeldoorn-cev-challenge': 1279,
  'draisma-dynamo-apeldoorn-ned-cev-challenge': 1323,
  'erzbergm-trofaiach-eisenerz-cev-challenge': 1306,
  'erzbergm-trofaiach-eisenerz-aut-cev-challenge': 1350,
  'fatum-ny-regyh-za-cev-challenge': 1296,
  'fatum-ny-regyh-za-hun-cev-challenge': 1340,
  'fleyr-t-rshavn-cev-challenge': 1293,
  'fleyr-t-rshavn-far-cev-challenge': 1337,
  'friso-sneek-cev-challenge': 1286,
  'friso-sneek-ned-cev-challenge': 1330,
  'fundaci-n-cajasol-andaluc-a-cev-challenge': 1282,
  'fundaci-n-cajasol-andaluc-a-esp-cev-challenge': 1326,
  'gs-panionios-nea-smyrni-cev-challenge': 1295,
  'gs-panionios-nea-smyrni-gre-cev-challenge': 1339,
  'gzok-srem-sremska-mitrovica-cev-challenge': 1275,
  'gzok-srem-sremska-mitrovica-srb-cev-challenge': 1319,
  'holte-if-cev-challenge': 1281,
  'holte-if-den-cev-challenge': 1325,
  'kaunas-vdu-cev-challenge': 1298,
  'kaunas-vdu-ltu-cev-challenge': 1342,
  'kv-fer-volley-ferizaj-cev-challenge': 1291,
  'kv-fer-volley-ferizaj-kos-cev-challenge': 1335,
  'levski-sofia-cev-challenge': 1289,
  'levski-sofia-bul-cev-challenge': 1333,
  'lp-salo-cev-challenge': 1297,
  'lp-salo-fin-cev-challenge': 1341,
  'nakovski-volej-strumica-cev-challenge': 1277,
  'nakovski-volej-strumica-mkd-cev-challenge': 1321,
  'ocisa-haro-rioja-cev-challenge': 1300,
  'ocisa-haro-rioja-esp-cev-challenge': 1344,
  'ok-brda-split-cev-challenge': 1284,
  'ok-brda-split-cro-cev-challenge': 1328,
  'ksyl-myre-cev-challenge': 1299,
  'ksyl-myre-nor-cev-challenge': 1343,
  'olympiada-neapolis-nicosia-cev-challenge': 1285,
  'olympiada-neapolis-nicosia-cyp-cev-challenge': 1329,
  'rabotnicki-skopje-cev-challenge': 1302,
  'rabotnicki-skopje-mkd-cev-challenge': 1346,
  'rae-spordikool-viaston-juri-cev-challenge': 1303,
  'rae-spordikool-viaston-juri-est-cev-challenge': 1347,
  'sc-balta-cev-challenge': 1307,
  'sc-balta-ukr-cev-challenge': 1351,
  'tchalou-chapelle-lez-herlaimont-cev-challenge': 1292,
  'tchalou-chapelle-lez-herlaimont-bel-cev-challenge': 1336,
  'tif-viking-bergen-cev-challenge': 1305,
  'tif-viking-bergen-nor-cev-challenge': 1349,
  'tj-ostrava-cev-challenge': 1276,
  'tj-ostrava-cze-cev-challenge': 1320,
  'va-uniza-zilina-cev-challenge': 1280,
  'va-uniza-zilina-svk-cev-challenge': 1324,
  'vbc-cheseaux-cev-challenge': 1288,
  'vbc-cheseaux-sui-cev-challenge': 1332,
  'vk-pirane-brusno-cev-challenge': 1304,
  'vk-pirane-brusno-svk-cev-challenge': 1348,
  'vk-prostejov-cev-challenge': 1278,
  'vk-prostejov-cze-cev-challenge': 1322,
  'vk-slovan-bratislava-cev-challenge': 1283,
  'vk-slovan-bratislava-svk-cev-challenge': 1327,
  'volley-dudingen-cev-challenge': 1290,
  'volley-dudingen-sui-cev-challenge': 1334,
  'winner-chcm-67-68-cev-challenge': 1308,
  'winner-chcw-69-70-cev-challenge': 1309,
  'winner-chcw-71-72-cev-challenge': 1310,
  'winner-chcw-73-74-cev-challenge': 1311,
  'winner-chcw-75-76-cev-challenge': 1312,
  'winner-chcw-77-78-cev-challenge': 1313,
  'winner-chcw-79-80-cev-challenge': 1314,
  'winner-chcw-81-82-cev-challenge': 1315,
  'winner-chcw-91-92-cev-challenge': 1316,
  'winner-chcw-93-94-cev-challenge': 1317
};

export const TEAMS: Record<TeamId, TeamInfo> = {
  1000: {"id":1000,"slug":"aras-kargo-vsl","name":"ARAS KARGO","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1001: {"id":1001,"slug":"aydin-buyuksehi-r-beledi-yespor-vsl","name":"AYDIN BÜYÜKŞEHİR BELEDİYESPOR","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1002: {"id":1002,"slug":"bahceli-evler-bld-vsl","name":"BAHÇELİEVLER BLD.","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1003: {"id":1003,"slug":"besi-ktas-vsl","name":"BEŞİKTAŞ","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1004: {"id":1004,"slug":"eczacibasi-dynavi-t-vsl","name":"ECZACIBAŞI DYNAVİT","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1005: {"id":1005,"slug":"fenerbahce-medicana-vsl","name":"FENERBAHÇE MEDICANA","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1006: {"id":1006,"slug":"galatasaray-daikin-vsl","name":"GALATASARAY DAIKIN","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1007: {"id":1007,"slug":"goztepe-vsl","name":"GÖZTEPE","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1013: {"id":1013,"slug":"i-lbank-vsl","name":"İLBANK","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1008: {"id":1008,"slug":"kuzeyboru-vsl","name":"KUZEYBORU","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1009: {"id":1009,"slug":"ni-lufer-beledi-yespor-eker-vsl","name":"NİLÜFER BELEDİYESPOR EKER","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1010: {"id":1010,"slug":"turk-hava-yollari-vsl","name":"TÜRK HAVA YOLLARI","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1011: {"id":1011,"slug":"vakifbank-vsl","name":"VAKIFBANK","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1012: {"id":1012,"slug":"zeren-spor-vsl","name":"ZEREN SPOR","league":"VSL","country":"TUR","groupName":"Vodafone Sultanlar Ligi"},
  1033: {"id":1033,"slug":"afyon-bld-yuntas-1lig","name":"AFYON BLD. YÜNTAŞ","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1030: {"id":1030,"slug":"alfemo-zeren-spor-1lig","name":"ALFEMO ZEREN SPOR","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1021: {"id":1021,"slug":"altinordu-1lig","name":"ALTINORDU","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1024: {"id":1024,"slug":"bodrum-bld-bodrumspor-1lig","name":"BODRUM BLD. BODRUMSPOR","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1015: {"id":1015,"slug":"canakkale-bld-1lig","name":"ÇANAKKALE BLD.","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1017: {"id":1017,"slug":"deni-zli-b-sehi-r-bld-1lig","name":"DENİZLİ B.ŞEHİR BLD.","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1029: {"id":1029,"slug":"di-yarbakir-b-sehi-r-bld-1lig","name":"DİYARBAKIR B.ŞEHİR BLD.","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1016: {"id":1016,"slug":"eczacibasi-1lig","name":"ECZACIBAŞI","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1022: {"id":1022,"slug":"endo-karsiyaka-1lig","name":"ENDO KARŞIYAKA","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1038: {"id":1038,"slug":"fdm-yapi-konya-eregli-bld-1lig","name":"FDM YAPI KONYA EREĞLİ BLD.","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1014: {"id":1014,"slug":"fenerbahce-medicana-1lig","name":"FENERBAHÇE MEDICANA","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1025: {"id":1025,"slug":"havran-bld-1lig","name":"HAVRAN BLD.","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1039: {"id":1039,"slug":"i-ba-ki-mya-ted-ankara-kolejli-ler-1lig","name":"İBA KİMYA TED ANKARA KOLEJLİLER","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1018: {"id":1018,"slug":"i-bb-spor-kulubu-1lig","name":"İBB SPOR KULÜBÜ","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1028: {"id":1028,"slug":"i-lbank-1lig","name":"İLBANK","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1032: {"id":1032,"slug":"karayollari-1lig","name":"KARAYOLLARI","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1026: {"id":1026,"slug":"kuzeyboru-maxi-pi-pe-spor-1lig","name":"KUZEYBORU MAXİPİPE SPOR","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1031: {"id":1031,"slug":"meri-nos-voleybol-1lig","name":"MERİNOS VOLEYBOL","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1036: {"id":1036,"slug":"muratpasa-bld-aci-koleji-1lig","name":"MURATPAŞA BLD. AÇI KOLEJİ","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1037: {"id":1037,"slug":"ptt-1lig","name":"PTT","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1027: {"id":1027,"slug":"sakarya-voleybol-1lig","name":"SAKARYA VOLEYBOL","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1035: {"id":1035,"slug":"si-gorta-shop-mke-ankaragucu-1lig","name":"SİGORTA SHOP MKE ANKARAGÜCÜ","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1034: {"id":1034,"slug":"trendy-hotels-manavgat-bld-1lig","name":"TRENDY HOTELS MANAVGAT BLD.","league":"1LIG","country":"TUR","groupName":"B. Grup"},
  1019: {"id":1019,"slug":"vakifbank-1lig","name":"VAKIFBANK","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1023: {"id":1023,"slug":"vestel-mani-sa-b-sehi-r-bld-1lig","name":"VESTEL MANİSA B.ŞEHİR BLD.","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1020: {"id":1020,"slug":"yesi-lyurt-1lig","name":"YEŞİLYURT","league":"1LIG","country":"TUR","groupName":"A. Grup"},
  1122: {"id":1122,"slug":"07-mega-spor-2lig","name":"07 MEGA SPOR","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1198: {"id":1198,"slug":"52-camlik-spor-2lig","name":"52 ÇAMLIK SPOR","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1216: {"id":1216,"slug":"73-sirnak-bld-2lig","name":"73 ŞIRNAK BLD.","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1212: {"id":1212,"slug":"91000-dev-spor-2lig","name":"91000 DEV SPOR","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1120: {"id":1120,"slug":"aci-koleji-2lig","name":"AÇI KOLEJİ","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1185: {"id":1185,"slug":"adana-b-sehi-r-bld-2lig","name":"ADANA B.ŞEHİR BLD.","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1183: {"id":1183,"slug":"adana-sporcu-egi-ti-m-spor-2lig","name":"ADANA SPORCU EĞİTİM SPOR","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1180: {"id":1180,"slug":"adana-t-d-s-2lig","name":"ADANA T.D.S.","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1129: {"id":1129,"slug":"afyon-gencli-k-spor-2lig","name":"AFYON GENÇLİK SPOR","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1160: {"id":1160,"slug":"ahmet-hamdi-tanpinar-ortaokulu-2lig","name":"AHMET HAMDİ TANPINAR ORTAOKULU","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1123: {"id":1123,"slug":"akdeni-z-bi-lgi-spor-2lig","name":"AKDENİZ BİLGİ SPOR","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1098: {"id":1098,"slug":"akhi-sar-bld-2lig","name":"AKHİSAR BLD.","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1097: {"id":1097,"slug":"akhi-sar-gucu-2lig","name":"AKHİSAR GÜCÜ","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1142: {"id":1142,"slug":"al-ka-altin-kanatlar-2lig","name":"AL-KA ALTIN KANATLAR","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1080: {"id":1080,"slug":"alp-spor-2lig","name":"ALP SPOR","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1093: {"id":1093,"slug":"altay-2lig","name":"ALTAY","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1099: {"id":1099,"slug":"altinay-spor-2lig","name":"ALTINAY SPOR","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1062: {"id":1062,"slug":"altinyurt-2lig","name":"ALTINYURT","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1157: {"id":1157,"slug":"ankara-barosu-2lig","name":"ANKARA BAROSU","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1168: {"id":1168,"slug":"ankara-dsi-2lig","name":"ANKARA DSİ","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1208: {"id":1208,"slug":"antepi-a-2lig","name":"ANTEPİA","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1107: {"id":1107,"slug":"arkas-spor-2lig","name":"ARKAS SPOR","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1047: {"id":1047,"slug":"arnavutkoy-bld-2lig","name":"ARNAVUTKÖY BLD.","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1187: {"id":1187,"slug":"arsavev-hatay-voleybol-2lig","name":"ARSAVEV HATAY VOLEYBOL","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1096: {"id":1096,"slug":"ata-okul-spor-2lig","name":"ATA OKUL SPOR","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1071: {"id":1071,"slug":"atasehi-r-kartallari-2lig","name":"ATAŞEHİR KARTALLARI","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1040: {"id":1040,"slug":"avrupa-voleybol-geli-si-m-2lig","name":"AVRUPA VOLEYBOL GELİŞİM","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1111: {"id":1111,"slug":"aydin-buyuksehi-r-beledi-yespor-2lig","name":"AYDIN BÜYÜKŞEHİR BELEDİYESPOR","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1176: {"id":1176,"slug":"b-sehi-r-bld-ankara-spor-2lig","name":"B.ŞEHİR BLD. ANKARA SPOR","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1052: {"id":1052,"slug":"bahceli-evler-bld-2lig","name":"BAHÇELİEVLER BLD.","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1131: {"id":1131,"slug":"bahcesehi-r-koleji-dalaman-bld-2lig","name":"BAHÇEŞEHİR KOLEJİ DALAMAN BLD.","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1082: {"id":1082,"slug":"balikesi-r-b-sehi-r-bld-2lig","name":"BALIKESİR B.ŞEHİR BLD.","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1090: {"id":1090,"slug":"balikesi-r-dsi-2lig","name":"BALIKESİR DSİ","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1083: {"id":1083,"slug":"bandirma-celi-k-spor-2lig","name":"BANDIRMA ÇELİK SPOR","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1149: {"id":1149,"slug":"bartin-volley-academy-2lig","name":"BARTIN VOLLEY ACADEMY","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1054: {"id":1054,"slug":"basaksehi-r-voleybol-2lig","name":"BAŞAKŞEHİR VOLEYBOL","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1155: {"id":1155,"slug":"baskent-ada-spor-2lig","name":"BAŞKENT ADA SPOR","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1170: {"id":1170,"slug":"baskent-zi-rve-2lig","name":"BAŞKENT ZİRVE","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1190: {"id":1190,"slug":"bayburt-gencli-k-merkezi-2lig","name":"BAYBURT GENÇLİK MERKEZİ","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1102: {"id":1102,"slug":"bayrakli-bld-2lig","name":"BAYRAKLI BLD.","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1104: {"id":1104,"slug":"bergama-bld-2lig","name":"BERGAMA BLD.","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1199: {"id":1199,"slug":"besi-kduzu-2lig","name":"BEŞİKDÜZÜ","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1055: {"id":1055,"slug":"besi-ktas-naviosa-2lig","name":"BEŞİKTAŞ NAVIOSA","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1042: {"id":1042,"slug":"beyli-kduzu-beykent-2lig","name":"BEYLİKDÜZÜ BEYKENT","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1044: {"id":1044,"slug":"bi-zi-mkent-voleybol-2lig","name":"BİZİMKENT VOLEYBOL","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1154: {"id":1154,"slug":"bolu-ataturk-anadolu-li-sesi-2lig","name":"BOLU ATATÜRK ANADOLU LİSESİ","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1136: {"id":1136,"slug":"bursa-b-sehi-r-bld-2lig","name":"BURSA B.ŞEHİR BLD.","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1134: {"id":1134,"slug":"bursa-fethi-ye-1973-spor-2lig","name":"BURSA FETHİYE 1973 SPOR","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1056: {"id":1056,"slug":"buyuk-resi-tpasa-ortaokulu-2lig","name":"BÜYÜK REŞİTPAŞA ORTAOKULU","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1050: {"id":1050,"slug":"buyukcekmece-voleybol-akademi-2lig","name":"BÜYÜKÇEKMECE VOLEYBOL AKADEMİ","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1146: {"id":1146,"slug":"cadence-boya-golcuk-i-hsani-ye-2lig","name":"CADENCE BOYA GÖLCÜK İHSANİYE","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1064: {"id":1064,"slug":"can-mi-lan-atleti-k-2lig","name":"CAN MİLAN ATLETİK","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1173: {"id":1173,"slug":"caba-spor-2lig","name":"ÇABA SPOR","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1087: {"id":1087,"slug":"can-kale-spor-2lig","name":"ÇAN KALE SPOR","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1085: {"id":1085,"slug":"canakkale-kepez-2lig","name":"ÇANAKKALE KEPEZ","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1041: {"id":1041,"slug":"catalca-bld-2lig","name":"ÇATALCA BLD.","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1077: {"id":1077,"slug":"cekmekoy-i-stanbul-spor-2lig","name":"ÇEKMEKÖY İSTANBUL SPOR","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1066: {"id":1066,"slug":"cengelkoy-voleybol-2lig","name":"ÇENGELKÖY VOLEYBOL","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1086: {"id":1086,"slug":"cerkezkoy-voleybol-akademi-2lig","name":"ÇERKEZKÖY VOLEYBOL AKADEMİ","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1092: {"id":1092,"slug":"corlu-bld-2lig","name":"ÇORLU BLD.","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1194: {"id":1194,"slug":"corum-arena-spor-2lig","name":"ÇORUM ARENA SPOR","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1201: {"id":1201,"slug":"corum-voleybol-2lig","name":"ÇORUM VOLEYBOL","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1125: {"id":1125,"slug":"deni-zli-b-sehi-r-bld-2lig","name":"DENİZLİ B.ŞEHİR BLD.","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1068: {"id":1068,"slug":"dev-atasehi-r-2lig","name":"DEV ATAŞEHİR","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1211: {"id":1211,"slug":"di-yarbakir-voleybolcular-2lig","name":"DİYARBAKIR VOLEYBOLCULAR","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1069: {"id":1069,"slug":"dogu-akademi-2lig","name":"DOĞU AKADEMİ","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1144: {"id":1144,"slug":"duzce-voleybol-2lig","name":"DÜZCE VOLEYBOL","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1095: {"id":1095,"slug":"efor-gencli-k-2lig","name":"EFOR GENÇLİK","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1220: {"id":1220,"slug":"elazig-bld-2lig","name":"ELAZIĞ BLD.","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1121: {"id":1121,"slug":"eli-t-akdeni-z-2lig","name":"ELİT AKDENİZ","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1118: {"id":1118,"slug":"endo-karsiyaka-2lig","name":"ENDO KARŞIYAKA","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1164: {"id":1164,"slug":"english-time-spor-2lig","name":"ENGLISH TIME SPOR","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1179: {"id":1179,"slug":"eregli-sumer-spor-2lig","name":"EREĞLİ SÜMER SPOR","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1167: {"id":1167,"slug":"eryaman-geli-si-m-2lig","name":"ERYAMAN GELİŞİM","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1135: {"id":1135,"slug":"eski-sehi-r-peyman-spor-2lig","name":"ESKİŞEHİR PEYMAN SPOR","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1143: {"id":1143,"slug":"eski-sehi-r-sehi-r-koleji-egt-kultur-2lig","name":"ESKİŞEHİR ŞEHİR KOLEJİ EĞT. KÜLTÜR","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1165: {"id":1165,"slug":"eti-mesgut-bld-geli-si-m-2lig","name":"ETİMESGUT BLD. GELİŞİM","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1061: {"id":1061,"slug":"eyupsultan-bld-2lig","name":"EYÜPSULTAN BLD.","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1072: {"id":1072,"slug":"fenerbahce-medicana-2lig","name":"FENERBAHÇE MEDICANA","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1126: {"id":1126,"slug":"fethi-ye-voleybol-2lig","name":"FETHİYE VOLEYBOL","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1206: {"id":1206,"slug":"firat-ozkan-2lig","name":"FIRAT ÖZKAN","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1106: {"id":1106,"slug":"forza-spor-2lig","name":"FORZA SPOR","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1070: {"id":1070,"slug":"galatasaray-2lig","name":"GALATASARAY","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1210: {"id":1210,"slug":"gazi-antep-bld-2lig","name":"GAZİANTEP BLD.","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1115: {"id":1115,"slug":"gazi-emi-r-bld-2lig","name":"GAZİEMİR BLD.","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1147: {"id":1147,"slug":"gebze-gencli-k-ve-spor-2lig","name":"GEBZE GENÇLİK VE SPOR","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1108: {"id":1108,"slug":"geli-si-m-koleji-2lig","name":"GELİŞİM KOLEJİ","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1133: {"id":1133,"slug":"gemli-k-i-sti-klal-spor-2lig","name":"GEMLİK İSTİKLAL SPOR","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1159: {"id":1159,"slug":"golbasi-i-ncek-spor-2lig","name":"GÖLBAŞI İNCEK SPOR","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1101: {"id":1101,"slug":"goztepe-2lig","name":"GÖZTEPE","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1053: {"id":1053,"slug":"gungoren-voleybol-2lig","name":"GÜNGÖREN VOLEYBOL","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1127: {"id":1127,"slug":"gural-premier-antalyaspor-2lig","name":"GÜRAL PREMIER ANTALYASPOR","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1163: {"id":1163,"slug":"hakan-akisik-spor-2lig","name":"HAKAN AKIŞIK SPOR","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1217: {"id":1217,"slug":"hakkari-maemtal-2lig","name":"HAKKARİ MAEMTAL","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1219: {"id":1219,"slug":"hakkari-sporti-f-faali-yetler-2lig","name":"HAKKARİ SPORTİF FAALİYETLER","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1148: {"id":1148,"slug":"harput-lahmacun-yahya-kaptan-2lig","name":"HARPUT LAHMACUN YAHYA KAPTAN","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1178: {"id":1178,"slug":"hedef-ankara-2lig","name":"HEDEF ANKARA","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1132: {"id":1132,"slug":"heki-moglu-global-connect-travel-bvi-2lig","name":"HEKİMOĞLU GLOBAL CONNECT TRAVEL BVİ","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1137: {"id":1137,"slug":"hoca-ahmet-yesevi-anadolu-l-es-voleybol--2lig","name":"HOCA AHMET YESEVİ ANADOLU L. ES VOLEYBOL AKADEMİ","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1192: {"id":1192,"slug":"hopa-beledi-ye-2lig","name":"HOPA BELEDİYE","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1124: {"id":1124,"slug":"isparta-gencli-k-spor-2lig","name":"ISPARTA GENÇLİK SPOR","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1158: {"id":1158,"slug":"i-lbank-2lig","name":"İLBANK","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1046: {"id":1046,"slug":"i-stanbul-bi-zi-mkent-spor-2lig","name":"İSTANBUL BİZİMKENT SPOR","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1114: {"id":1114,"slug":"i-zmi-r-b-sehir-bld-2lig","name":"İZMİR B.ŞEHIR BLD.","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1116: {"id":1116,"slug":"i-zmi-r-dsi-2lig","name":"İZMİR DSİ","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1151: {"id":1151,"slug":"i-zmi-t-spor-2lig","name":"İZMİT SPOR","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1074: {"id":1074,"slug":"kamari-n-spor-2lig","name":"KAMARİN SPOR","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1145: {"id":1145,"slug":"karabuk-gencli-k-spor-2lig","name":"KARABÜK GENÇLİK SPOR","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1078: {"id":1078,"slug":"kartal-anadolu-2lig","name":"KARTAL ANADOLU","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1079: {"id":1079,"slug":"kartal-bld-2lig","name":"KARTAL BLD.","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1169: {"id":1169,"slug":"kavak-spor-2lig","name":"KAVAK SPOR","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1203: {"id":1203,"slug":"kayseri-ci-mnasti-k-spor-2lig","name":"KAYSERİ CİMNASTİK SPOR","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1204: {"id":1204,"slug":"kayseri-voleybol-2lig","name":"KAYSERİ VOLEYBOL","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1089: {"id":1089,"slug":"kirklareli-gencli-k-spor-2lig","name":"KIRKLARELİ GENÇLİK SPOR","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1150: {"id":1150,"slug":"kocaeli-ni-comedi-a-akademi-2lig","name":"KOCAELİ NİCOMEDİA AKADEMİ","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1153: {"id":1153,"slug":"kocaeli-voleybol-akademi-2lig","name":"KOCAELİ VOLEYBOL AKADEMİ","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1081: {"id":1081,"slug":"kuzey-yildizlari-2lig","name":"KUZEY YILDIZLARI","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1048: {"id":1048,"slug":"kucukcekmece-voleybol-2lig","name":"KÜÇÜKÇEKMECE VOLEYBOL","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1103: {"id":1103,"slug":"kzy-spor-2lig","name":"KZY SPOR","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1065: {"id":1065,"slug":"lanueva-kozmeti-k-anadolu-marmara-2lig","name":"LANUEVA KOZMETİK ANADOLU MARMARA","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1067: {"id":1067,"slug":"mac-sayisi-2lig","name":"MAÇ SAYISI","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1214: {"id":1214,"slug":"malatya-voleybol-2lig","name":"MALATYA VOLEYBOL","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1213: {"id":1213,"slug":"margenc-2lig","name":"MARGENÇ","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1130: {"id":1130,"slug":"marmari-s-bld-2lig","name":"MARMARİS BLD.","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1084: {"id":1084,"slug":"media-first-ayvalik-geli-si-m-spor-2lig","name":"MEDIA FIRST AYVALIK GELİŞİM SPOR","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1140: {"id":1140,"slug":"mehmet-ege-i-nsaat-i-negol-orhani-ye-vol-2lig","name":"MEHMET EGE İNŞAAT İNEGÖL ORHANİYE VOLEYBOL","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1075: {"id":1075,"slug":"mehmet-erdem-marmara-akademi-2lig","name":"MEHMET ERDEM MARMARA AKADEMİ","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1205: {"id":1205,"slug":"meri-nos-voleybol-2lig","name":"MERİNOS VOLEYBOL","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1138: {"id":1138,"slug":"mg-spor-2lig","name":"MG SPOR","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1174: {"id":1174,"slug":"misiroglu-beytepe-2lig","name":"MISIROĞLU BEYTEPE","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1172: {"id":1172,"slug":"mke-ankaragucu-2lig","name":"MKE ANKARAGÜCÜ","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1215: {"id":1215,"slug":"mus-oli-mpi-k-spor-2lig","name":"MUŞ OLİMPİK SPOR","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1218: {"id":1218,"slug":"ni-cer-hotel-voleybol-2lig","name":"NİCER HOTEL VOLEYBOL","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1139: {"id":1139,"slug":"ni-lufer-bld-2lig","name":"NİLÜFER BLD.","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1184: {"id":1184,"slug":"okura-loji-sti-k-mersi-n-i-hti-sas-2lig","name":"OKURA LOJİSTİK MERSİN İHTİSAS","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1196: {"id":1196,"slug":"osmancik-bld-2lig","name":"OSMANCIK BLD.","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1109: {"id":1109,"slug":"polat-group-di-di-m-beledi-yespor-2lig","name":"POLAT GROUP DİDİM BELEDİYESPOR","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1177: {"id":1177,"slug":"polatli-duatepe-2lig","name":"POLATLI DUATEPE","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1166: {"id":1166,"slug":"ptt-2lig","name":"PTT","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1200: {"id":1200,"slug":"ri-ze-endustri-meslek-li-sesi-2lig","name":"RİZE ENDÜSTRİ MESLEK LİSESİ","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1058: {"id":1058,"slug":"roberteam-2lig","name":"ROBERTEAM","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1112: {"id":1112,"slug":"rota-koleji-2lig","name":"ROTA KOLEJİ","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1197: {"id":1197,"slug":"semt-asansor-bordo-mavi-61-2lig","name":"SEMT ASANSÖR BORDO MAVİ 61","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1152: {"id":1152,"slug":"serdi-van-bld-2lig","name":"SERDİVAN BLD.","league":"2LIG","country":"TUR","groupName":"10. GRUP"},
  1182: {"id":1182,"slug":"seyhan-bld-2lig","name":"SEYHAN BLD.","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1191: {"id":1191,"slug":"sinav-koleji-samsunspor-2lig","name":"SINAV KOLEJİ SAMSUNSPOR","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1189: {"id":1189,"slug":"si-banet-kozan-i-mamoglu-spor-2lig","name":"SİBANET KOZAN İMAMOĞLU SPOR","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1049: {"id":1049,"slug":"si-li-vri-cagribey-2lig","name":"SİLİVRİ ÇAĞRIBEY","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1222: {"id":1222,"slug":"si-lopi-bld-sporti-f-faali-yetler-2lig","name":"SİLOPİ BLD. SPORTİF FAALİYETLER","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1221: {"id":1221,"slug":"si-lopi-geli-si-m-faali-yetleri-2lig","name":"SİLOPİ GELİŞİM FAALİYETLERİ","league":"2LIG","country":"TUR","groupName":"16. GRUP"},
  1209: {"id":1209,"slug":"si-vas-toprak-gayri-menkul-pars-akademi-2lig","name":"SİVAS TOPRAK GAYRİMENKUL PARS AKADEMİ","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1045: {"id":1045,"slug":"smac-spor-2lig","name":"SMAÇ SPOR","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1195: {"id":1195,"slug":"smart-holding-a-s-cayeli-2lig","name":"SMART HOLDING A.Ş. ÇAYELI","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1113: {"id":1113,"slug":"soke-beledi-ye-saldos-voleybol-2lig","name":"SÖKE BELEDİYE SALDOS VOLEYBOL","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1193: {"id":1193,"slug":"superpool-findikli-1974-2lig","name":"SUPERPOOL FINDIKLI 1974","league":"2LIG","country":"TUR","groupName":"14. GRUP"},
  1181: {"id":1181,"slug":"tarsus-ameri-kan-koleji-2lig","name":"TARSUS AMERİKAN KOLEJİ","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1175: {"id":1175,"slug":"ted-ankara-kolejli-ler-2lig","name":"TED ANKARA KOLEJLİLER","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1161: {"id":1161,"slug":"tek-metal-sporti-f-2lig","name":"TEK METAL SPORTİF","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1091: {"id":1091,"slug":"teki-rdag-voleybol-i-hti-sas-2lig","name":"TEKİRDAĞ VOLEYBOL İHTİSAS","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1156: {"id":1156,"slug":"temi-z-enerji-birli-gi-2lig","name":"TEMİZ ENERJİ BIRLİĞİ","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1188: {"id":1188,"slug":"toros-universi-tesi-volgem-2lig","name":"TOROS ÜNIVERSİTESİ VOLGEM","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1186: {"id":1186,"slug":"toroslar-bld-2lig","name":"TOROSLAR BLD.","league":"2LIG","country":"TUR","groupName":"13. GRUP"},
  1073: {"id":1073,"slug":"toyzz-shop-di-namo-spor-2lig","name":"TOYZZ SHOP DİNAMO SPOR","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1105: {"id":1105,"slug":"turgutlu-bld-kultur-sanat-2lig","name":"TURGUTLU BLD. KÜLTÜR SANAT","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1076: {"id":1076,"slug":"tuzla-mercan-2lig","name":"TUZLA MERCAN","league":"2LIG","country":"TUR","groupName":"4. GRUP"},
  1043: {"id":1043,"slug":"turk-hava-yollari-2lig","name":"TÜRK HAVA YOLLARI","league":"2LIG","country":"TUR","groupName":"1. GRUP"},
  1094: {"id":1094,"slug":"turkoglu-spor-kulubu-2lig","name":"TÜRKOĞLU SPOR KULÜBÜ","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1162: {"id":1162,"slug":"tvf-spor-li-sesi-2lig","name":"TVF SPOR LİSESİ","league":"2LIG","country":"TUR","groupName":"11. GRUP"},
  1128: {"id":1128,"slug":"uysallar-oto-fethi-ye-zi-rve-2lig","name":"UYSALLAR OTO FETHİYE ZİRVE","league":"2LIG","country":"TUR","groupName":"8. GRUP"},
  1110: {"id":1110,"slug":"ulku-spor-2lig","name":"ÜLKÜ SPOR","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1051: {"id":1051,"slug":"unsped-2lig","name":"ÜNSPED","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1060: {"id":1060,"slug":"vefa-2lig","name":"VEFA","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1117: {"id":1117,"slug":"venus-spor-2lig","name":"VENÜS SPOR","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1207: {"id":1207,"slug":"vi-ransehi-r-voleybol-2lig","name":"VİRANŞEHİR VOLEYBOL","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1119: {"id":1119,"slug":"volkan-guc-spor-2lig","name":"VOLKAN GÜÇ SPOR","league":"2LIG","country":"TUR","groupName":"7. GRUP"},
  1063: {"id":1063,"slug":"world-medicine-ates-spor-2lig","name":"WORLD MEDICINE ATEŞ SPOR","league":"2LIG","country":"TUR","groupName":"3. GRUP"},
  1141: {"id":1141,"slug":"yalova-ci-ftli-kkoy-bld-2lig","name":"YALOVA ÇİFTLİKKÖY BLD.","league":"2LIG","country":"TUR","groupName":"9. GRUP"},
  1171: {"id":1171,"slug":"yedi-dag-spor-2lig","name":"YEDİDAĞ SPOR","league":"2LIG","country":"TUR","groupName":"12. GRUP"},
  1057: {"id":1057,"slug":"yeni-ay-loji-sti-k-sariyer-konak-spor-2lig","name":"YENİAY LOJİSTİK SARIYER KONAK SPOR","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1088: {"id":1088,"slug":"yesi-l-bayrami-c-2lig","name":"YEŞİL BAYRAMİÇ","league":"2LIG","country":"TUR","groupName":"5. GRUP"},
  1059: {"id":1059,"slug":"yesi-lyurt-2lig","name":"YEŞİLYURT","league":"2LIG","country":"TUR","groupName":"2. GRUP"},
  1100: {"id":1100,"slug":"yunusemre-bld-2lig","name":"YUNUSEMRE BLD.","league":"2LIG","country":"TUR","groupName":"6. GRUP"},
  1202: {"id":1202,"slug":"zeugma-gazi-antep-spor-2lig","name":"ZEUGMA GAZİANTEP SPOR","league":"2LIG","country":"TUR","groupName":"15. GRUP"},
  1235: {"id":1235,"slug":"a-carraro-prosecco-doc-conegliano-cev-cl","name":"A. Carraro Prosecco DOC CONEGLIANO","league":"CEV_CL","country":null,"groupName":"Pool D"},
  1236: {"id":1236,"slug":"ankara-zeren-spor-kulubu-cev-cl","name":"ANKARA Zeren Spor Kulübü","league":"CEV_CL","country":null,"groupName":"Pool D"},
  1225: {"id":1225,"slug":"cs-volei-alba-blaj-cev-cl","name":"CS Volei Alba BLAJ","league":"CEV_CL","country":null,"groupName":"Pool A"},
  1237: {"id":1237,"slug":"dresdner-sc-cev-cl","name":"DRESDNER SC","league":"CEV_CL","country":null,"groupName":"Pool D"},
  1232: {"id":1232,"slug":"eczacibasi-istanbul-cev-cl","name":"Eczacibasi ISTANBUL","league":"CEV_CL","country":null,"groupName":"Pool C"},
  1227: {"id":1227,"slug":"fenerbahce-medicana-istanbul-cev-cl","name":"Fenerbahçe Medicana ISTANBUL","league":"CEV_CL","country":null,"groupName":"Pool B"},
  1228: {"id":1228,"slug":"igor-gorgonzola-novara-cev-cl","name":"Igor Gorgonzola NOVARA","league":"CEV_CL","country":null,"groupName":"Pool B"},
  1240: {"id":1240,"slug":"ks-developres-rzesz-w-cev-cl","name":"KS Developres RZESZÓW","league":"CEV_CL","country":null,"groupName":"Pool E"},
  1241: {"id":1241,"slug":"levallois-paris-saint-cloud-cev-cl","name":"LEVALLOIS PARIS Saint Cloud","league":"CEV_CL","country":null,"groupName":"Pool E"},
  1238: {"id":1238,"slug":"ks-commercecon-d-cev-cl","name":"ŁKS Commercecon ŁÓDŹ","league":"CEV_CL","country":null,"groupName":"Pool D"},
  1242: {"id":1242,"slug":"maritza-plovdiv-cev-cl","name":"Maritza PLOVDIV","league":"CEV_CL","country":null,"groupName":"Pool E"},
  1231: {"id":1231,"slug":"numia-vero-volley-milano-cev-cl","name":"Numia Vero Volley MILANO","league":"CEV_CL","country":null,"groupName":"Pool C"},
  1234: {"id":1234,"slug":"ok-elezni-ar-lajkovac-cev-cl","name":"OK Železničar LAJKOVAC","league":"CEV_CL","country":null,"groupName":"Pool C"},
  1233: {"id":1233,"slug":"olympiacos-piraeus-cev-cl","name":"Olympiacos PIRAEUS","league":"CEV_CL","country":null,"groupName":"Pool C"},
  1230: {"id":1230,"slug":"pge-budowlani-d-cev-cl","name":"PGE Budowlani ŁÓDŹ","league":"CEV_CL","country":null,"groupName":"Pool B"},
  1223: {"id":1223,"slug":"savino-del-bene-scandicci-cev-cl","name":"Savino Del Bene SCANDICCI","league":"CEV_CL","country":null,"groupName":"Pool A"},
  1229: {"id":1229,"slug":"sport-lisboa-e-benfica-cev-cl","name":"Sport LISBOA e Benfica","league":"CEV_CL","country":null,"groupName":"Pool B"},
  1239: {"id":1239,"slug":"ssc-palmberg-schwerin-cev-cl","name":"SSC Palmberg SCHWERIN","league":"CEV_CL","country":null,"groupName":"Pool E"},
  1224: {"id":1224,"slug":"vakifbank-istanbul-cev-cl","name":"VakifBank ISTANBUL","league":"CEV_CL","country":null,"groupName":"Pool A"},
  1226: {"id":1226,"slug":"volero-le-cannet-cev-cl","name":"Volero LE CANNET","league":"CEV_CL","country":null,"groupName":"Pool A"},
  1266: {"id":1266,"slug":"ac-paok-thessaloniki-cev-cup","name":"AC PAOK THESSALONIKI","league":"CEV_CUP","country":"GRE","groupName":null},
  1245: {"id":1245,"slug":"allianz-mtv-stuttgart-cev-cup","name":"Allianz MTV STUTTGART","league":"CEV_CUP","country":"GER","groupName":null},
  1260: {"id":1260,"slug":"asterix-avo-beveren-cev-cup","name":"Asterix Avo BEVEREN","league":"CEV_CUP","country":"BEL","groupName":null},
  1268: {"id":1268,"slug":"avarca-de-menorca-cev-cup","name":"Avarca de MENORCA","league":"CEV_CUP","country":"ESP","groupName":null},
  1252: {"id":1252,"slug":"bks-bostik-bielsko-bia-a-cev-cup","name":"BKS Bostik BIELSKO-BIAŁA","league":"CEV_CUP","country":"POL","groupName":null},
  1247: {"id":1247,"slug":"c-s-o-voluntari-2005-cev-cup","name":"C.S.O. VOLUNTARI 2005","league":"CEV_CUP","country":"ROU","groupName":null},
  1267: {"id":1267,"slug":"cd-heidelberg-las-palmas-cev-cup","name":"CD Heidelberg LAS PALMAS","league":"CEV_CUP","country":"ESP","groupName":null},
  1259: {"id":1259,"slug":"darta-bevo-roeselare-cev-cup","name":"Darta Bevo ROESELARE","league":"CEV_CUP","country":"BEL","groupName":null},
  1248: {"id":1248,"slug":"dinamo-bucuresti-cev-cup","name":"Dinamo BUCURESTI","league":"CEV_CUP","country":"ROU","groupName":null},
  1265: {"id":1265,"slug":"dukla-liberec-cev-cup","name":"Dukla LIBEREC","league":"CEV_CUP","country":"CZE","groupName":null},
  1261: {"id":1261,"slug":"fc-porto-cev-cup","name":"FC PORTO","league":"CEV_CUP","country":"POR","groupName":null},
  1243: {"id":1243,"slug":"galatasaray-daikin-istanbul-cev-cup","name":"Galatasaray Daikin ISTANBUL","league":"CEV_CUP","country":"TUR","groupName":null},
  1273: {"id":1273,"slug":"janta-volej-kisela-voda-cev-cup","name":"Janta Volej KISELA VODA","league":"CEV_CUP","country":"MKD","groupName":null},
  1255: {"id":1255,"slug":"mbh-b-k-scsaba-cev-cup","name":"MBH - BÉKÉSCSABA","league":"CEV_CUP","country":"HUN","groupName":null},
  1257: {"id":1257,"slug":"mladost-zagreb-cev-cup","name":"Mladost ZAGREB","league":"CEV_CUP","country":"CRO","groupName":null},
  1253: {"id":1253,"slug":"moya-radomka-radom-cev-cup","name":"MOYA Radomka RADOM","league":"CEV_CUP","country":"POL","groupName":null},
  1258: {"id":1258,"slug":"ok-dinamo-zagreb-cev-cup","name":"OK Dinamo ZAGREB","league":"CEV_CUP","country":"CRO","groupName":null},
  1254: {"id":1254,"slug":"otp-banka-branik-maribor-cev-cup","name":"OTP Banka Branik MARIBOR","league":"CEV_CUP","country":"SLO","groupName":null},
  1249: {"id":1249,"slug":"reale-mutua-fenera-chieri-76-cev-cup","name":"Reale Mutua Fenera CHIERI'76","league":"CEV_CUP","country":"ITA","groupName":null},
  1262: {"id":1262,"slug":"sporting-cp-lisboa-cev-cup","name":"Sporting CP LISBOA","league":"CEV_CUP","country":"POR","groupName":null},
  1269: {"id":1269,"slug":"tent-obrenovac-cev-cup","name":"Tent OBRENOVAC","league":"CEV_CUP","country":"SRB","groupName":null},
  1244: {"id":1244,"slug":"thy-istanbul-cev-cup","name":"THY ISTANBUL","league":"CEV_CUP","country":"TUR","groupName":null},
  1251: {"id":1251,"slug":"vandoeuvre-nancy-vb-cev-cup","name":"Vandoeuvre NANCY VB","league":"CEV_CUP","country":"FRA","groupName":null},
  1256: {"id":1256,"slug":"vasas-buda-budapest-cev-cup","name":"Vasas Óbuda BUDAPEST","league":"CEV_CUP","country":"HUN","groupName":null},
  1246: {"id":1246,"slug":"vfb-suhl-thuringen-cev-cup","name":"VfB SUHL Thüringen","league":"CEV_CUP","country":"GER","groupName":null},
  1263: {"id":1263,"slug":"viteos-neuchatel-uc-cev-cup","name":"Viteos NEUCHATEL UC","league":"CEV_CUP","country":"SUI","groupName":null},
  1264: {"id":1264,"slug":"vk-up-olomouc-cev-cup","name":"VK UP OLOMOUC","league":"CEV_CUP","country":"CZE","groupName":null},
  1250: {"id":1250,"slug":"volley-mulhouse-alsace-cev-cup","name":"Volley MULHOUSE Alsace","league":"CEV_CUP","country":"FRA","groupName":null},
  1272: {"id":1272,"slug":"ok-gacko-rd-swisslion-cev-cup","name":"ŽOK GACKO RD Swisslion","league":"CEV_CUP","country":"BIH","groupName":null},
  1271: {"id":1271,"slug":"ok-ribola-ka-tela-cev-cup","name":"ŽOK Ribola KAŠTELA","league":"CEV_CUP","country":"CRO","groupName":null},
  1270: {"id":1270,"slug":"zok-ub-cev-cup","name":"ZOK UB","league":"CEV_CUP","country":"SRB","groupName":null},
  1274: {"id":1274,"slug":"aek-athens-cev-challenge","name":"AEK ATHENS","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1318: {"id":1318,"slug":"aek-athens-gre-cev-challenge","name":"AEK ATHENS GRE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1294: {"id":1294,"slug":"ao-thiras-cev-challenge","name":"AO THIRAS","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1338: {"id":1338,"slug":"ao-thiras-gre-cev-challenge","name":"AO THIRAS GRE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1301: {"id":1301,"slug":"buducnost-podgorica-cev-challenge","name":"Buducnost PODGORICA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1345: {"id":1345,"slug":"buducnost-podgorica-mne-cev-challenge","name":"Buducnost PODGORICA MNE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1287: {"id":1287,"slug":"c-s-m-lugoj-cev-challenge","name":"C.S.M LUGOJ","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1331: {"id":1331,"slug":"c-s-m-lugoj-rou-cev-challenge","name":"C.S.M LUGOJ ROU","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1279: {"id":1279,"slug":"draisma-dynamo-apeldoorn-cev-challenge","name":"Draisma Dynamo APELDOORN","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1323: {"id":1323,"slug":"draisma-dynamo-apeldoorn-ned-cev-challenge","name":"Draisma Dynamo APELDOORN NED","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1306: {"id":1306,"slug":"erzbergm-trofaiach-eisenerz-cev-challenge","name":"Erzbergm TROFAIACH EISENERZ","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1350: {"id":1350,"slug":"erzbergm-trofaiach-eisenerz-aut-cev-challenge","name":"Erzbergm TROFAIACH EISENERZ AUT","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1296: {"id":1296,"slug":"fatum-ny-regyh-za-cev-challenge","name":"Fatum NYÍREGYHÁZA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1340: {"id":1340,"slug":"fatum-ny-regyh-za-hun-cev-challenge","name":"Fatum NYÍREGYHÁZA HUN","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1293: {"id":1293,"slug":"fleyr-t-rshavn-cev-challenge","name":"Fleyr TÓRSHAVN","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1337: {"id":1337,"slug":"fleyr-t-rshavn-far-cev-challenge","name":"Fleyr TÓRSHAVN FAR","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1286: {"id":1286,"slug":"friso-sneek-cev-challenge","name":"Friso SNEEK","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1330: {"id":1330,"slug":"friso-sneek-ned-cev-challenge","name":"Friso SNEEK NED","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1282: {"id":1282,"slug":"fundaci-n-cajasol-andaluc-a-cev-challenge","name":"Fundación Cajasol ANDALUCÍA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1326: {"id":1326,"slug":"fundaci-n-cajasol-andaluc-a-esp-cev-challenge","name":"Fundación Cajasol ANDALUCÍA ESP","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1295: {"id":1295,"slug":"gs-panionios-nea-smyrni-cev-challenge","name":"GS Panionios NEA SMYRNI","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1339: {"id":1339,"slug":"gs-panionios-nea-smyrni-gre-cev-challenge","name":"GS Panionios NEA SMYRNI GRE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1275: {"id":1275,"slug":"gzok-srem-sremska-mitrovica-cev-challenge","name":"GZOK Srem SREMSKA MITROVICA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1319: {"id":1319,"slug":"gzok-srem-sremska-mitrovica-srb-cev-challenge","name":"GZOK Srem SREMSKA MITROVICA SRB","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1281: {"id":1281,"slug":"holte-if-cev-challenge","name":"HOLTE IF","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1325: {"id":1325,"slug":"holte-if-den-cev-challenge","name":"HOLTE IF DEN","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1298: {"id":1298,"slug":"kaunas-vdu-cev-challenge","name":"KAUNAS VDU","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1342: {"id":1342,"slug":"kaunas-vdu-ltu-cev-challenge","name":"KAUNAS VDU LTU","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1291: {"id":1291,"slug":"kv-fer-volley-ferizaj-cev-challenge","name":"KV Fer Volley FERIZAJ","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1335: {"id":1335,"slug":"kv-fer-volley-ferizaj-kos-cev-challenge","name":"KV Fer Volley FERIZAJ KOS","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1289: {"id":1289,"slug":"levski-sofia-cev-challenge","name":"Levski SOFIA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1333: {"id":1333,"slug":"levski-sofia-bul-cev-challenge","name":"Levski SOFIA BUL","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1297: {"id":1297,"slug":"lp-salo-cev-challenge","name":"LP SALO","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1341: {"id":1341,"slug":"lp-salo-fin-cev-challenge","name":"LP SALO FIN","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1277: {"id":1277,"slug":"nakovski-volej-strumica-cev-challenge","name":"Nakovski Volej STRUMICA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1321: {"id":1321,"slug":"nakovski-volej-strumica-mkd-cev-challenge","name":"Nakovski Volej STRUMICA MKD","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1300: {"id":1300,"slug":"ocisa-haro-rioja-cev-challenge","name":"Ocisa HARO Rioja","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1344: {"id":1344,"slug":"ocisa-haro-rioja-esp-cev-challenge","name":"Ocisa HARO Rioja ESP","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1284: {"id":1284,"slug":"ok-brda-split-cev-challenge","name":"OK BRDA SPLIT","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1328: {"id":1328,"slug":"ok-brda-split-cro-cev-challenge","name":"OK BRDA SPLIT CRO","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1299: {"id":1299,"slug":"ksyl-myre-cev-challenge","name":"Øksyl MYRE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1343: {"id":1343,"slug":"ksyl-myre-nor-cev-challenge","name":"Øksyl MYRE NOR","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1285: {"id":1285,"slug":"olympiada-neapolis-nicosia-cev-challenge","name":"Olympiada Neapolis NICOSIA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1329: {"id":1329,"slug":"olympiada-neapolis-nicosia-cyp-cev-challenge","name":"Olympiada Neapolis NICOSIA CYP","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1302: {"id":1302,"slug":"rabotnicki-skopje-cev-challenge","name":"Rabotnicki SKOPJE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1346: {"id":1346,"slug":"rabotnicki-skopje-mkd-cev-challenge","name":"Rabotnicki SKOPJE MKD","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1303: {"id":1303,"slug":"rae-spordikool-viaston-juri-cev-challenge","name":"RAE Spordikool Viaston JÜRI","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1347: {"id":1347,"slug":"rae-spordikool-viaston-juri-est-cev-challenge","name":"RAE Spordikool Viaston JÜRI EST","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1307: {"id":1307,"slug":"sc-balta-cev-challenge","name":"SC BALTA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1351: {"id":1351,"slug":"sc-balta-ukr-cev-challenge","name":"SC BALTA UKR","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1292: {"id":1292,"slug":"tchalou-chapelle-lez-herlaimont-cev-challenge","name":"Tchalou CHAPELLE-LEZ-HERLAIMONT","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1336: {"id":1336,"slug":"tchalou-chapelle-lez-herlaimont-bel-cev-challenge","name":"Tchalou CHAPELLE-LEZ-HERLAIMONT BEL","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1305: {"id":1305,"slug":"tif-viking-bergen-cev-challenge","name":"TIF Viking BERGEN","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1349: {"id":1349,"slug":"tif-viking-bergen-nor-cev-challenge","name":"TIF Viking BERGEN NOR","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1276: {"id":1276,"slug":"tj-ostrava-cev-challenge","name":"TJ OSTRAVA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1320: {"id":1320,"slug":"tj-ostrava-cze-cev-challenge","name":"TJ OSTRAVA CZE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1280: {"id":1280,"slug":"va-uniza-zilina-cev-challenge","name":"VA Uniza ZILINA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1324: {"id":1324,"slug":"va-uniza-zilina-svk-cev-challenge","name":"VA Uniza ZILINA SVK","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1288: {"id":1288,"slug":"vbc-cheseaux-cev-challenge","name":"VBC CHESEAUX","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1332: {"id":1332,"slug":"vbc-cheseaux-sui-cev-challenge","name":"VBC CHESEAUX SUI","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1304: {"id":1304,"slug":"vk-pirane-brusno-cev-challenge","name":"VK Pirane BRUSNO","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1348: {"id":1348,"slug":"vk-pirane-brusno-svk-cev-challenge","name":"VK Pirane BRUSNO SVK","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1278: {"id":1278,"slug":"vk-prostejov-cev-challenge","name":"VK PROSTEJOV","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1322: {"id":1322,"slug":"vk-prostejov-cze-cev-challenge","name":"VK PROSTEJOV CZE","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1283: {"id":1283,"slug":"vk-slovan-bratislava-cev-challenge","name":"VK Slovan BRATISLAVA","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1327: {"id":1327,"slug":"vk-slovan-bratislava-svk-cev-challenge","name":"VK Slovan BRATISLAVA SVK","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1290: {"id":1290,"slug":"volley-dudingen-cev-challenge","name":"Volley DÜDINGEN","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1334: {"id":1334,"slug":"volley-dudingen-sui-cev-challenge","name":"Volley DÜDINGEN SUI","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1308: {"id":1308,"slug":"winner-chcm-67-68-cev-challenge","name":"Winner CHCM 67/68","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1309: {"id":1309,"slug":"winner-chcw-69-70-cev-challenge","name":"Winner CHCW 69/70","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1310: {"id":1310,"slug":"winner-chcw-71-72-cev-challenge","name":"Winner CHCW 71/72","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1311: {"id":1311,"slug":"winner-chcw-73-74-cev-challenge","name":"Winner CHCW 73/74","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1312: {"id":1312,"slug":"winner-chcw-75-76-cev-challenge","name":"Winner CHCW 75/76","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1313: {"id":1313,"slug":"winner-chcw-77-78-cev-challenge","name":"Winner CHCW 77/78","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1314: {"id":1314,"slug":"winner-chcw-79-80-cev-challenge","name":"Winner CHCW 79/80","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1315: {"id":1315,"slug":"winner-chcw-81-82-cev-challenge","name":"Winner CHCW 81/82","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1316: {"id":1316,"slug":"winner-chcw-91-92-cev-challenge","name":"Winner CHCW 91/92","league":"CEV_CHALLENGE","country":null,"groupName":null},
  1317: {"id":1317,"slug":"winner-chcw-93-94-cev-challenge","name":"Winner CHCW 93/94","league":"CEV_CHALLENGE","country":null,"groupName":null}
};

export type ClubId = 
  | 'CLUB_FENERBAHCE'
  | 'CLUB_GALATASARAY'
  | 'CLUB_BESIKTAS'
  | 'CLUB_ECZACIBASI'
  | 'CLUB_VAKIFBANK'
  | 'CLUB_THY'
  | 'CLUB_ZEREN'
  | 'CLUB_ILBANK'
  | 'CLUB_AYDIN_BSB'
  | 'CLUB_BAHCELIEVLER'
  | 'CLUB_GOZTEPE'
  | 'CLUB_DENIZLI_BSB'
  | 'CLUB_KARSIYAKA'
  | 'CLUB_MERINOS'
  | 'CLUB_PTT'
  | 'CLUB_YESILYURT'
  | 'CLUB_NILUFER'
  | 'CLUB_KUZEYBORU'
  | 'CLUB_ARAS_KARGO'
  | 'CLUB_BURSA_BSB'
  | 'CLUB_IZMIR_BSB'
  | 'CLUB_ISTANBULBBSK'
  | null;

export const CLUBS: Record<string, { clubId: ClubId; teams: TeamId[] }> = {
  'CLUB_ARAS_KARGO': { clubId: 'CLUB_ARAS_KARGO', teams: [1000] },
  'CLUB_AYDIN_BSB': { clubId: 'CLUB_AYDIN_BSB', teams: [1001, 1111] },
  'CLUB_BAHCELIEVLER': { clubId: 'CLUB_BAHCELIEVLER', teams: [1002, 1052] },
  'CLUB_BESIKTAS': { clubId: 'CLUB_BESIKTAS', teams: [1003, 1055] },
  'CLUB_ECZACIBASI': { clubId: 'CLUB_ECZACIBASI', teams: [1004, 1016, 1232] },
  'CLUB_FENERBAHCE': { clubId: 'CLUB_FENERBAHCE', teams: [1005, 1014, 1072, 1227] },
  'CLUB_GALATASARAY': { clubId: 'CLUB_GALATASARAY', teams: [1006, 1070, 1243] },
  'CLUB_GOZTEPE': { clubId: 'CLUB_GOZTEPE', teams: [1007, 1101] },
  'CLUB_ILBANK': { clubId: 'CLUB_ILBANK', teams: [1013, 1028, 1158] },
  'CLUB_KUZEYBORU': { clubId: 'CLUB_KUZEYBORU', teams: [1008, 1026] },
  'CLUB_NILUFER': { clubId: 'CLUB_NILUFER', teams: [1009, 1139] },
  'CLUB_THY': { clubId: 'CLUB_THY', teams: [1010, 1043, 1244] },
  'CLUB_VAKIFBANK': { clubId: 'CLUB_VAKIFBANK', teams: [1011, 1019, 1224] },
  'CLUB_ZEREN': { clubId: 'CLUB_ZEREN', teams: [1012, 1030, 1236] },
  'CLUB_DENIZLI_BSB': { clubId: 'CLUB_DENIZLI_BSB', teams: [1017, 1125] },
  'CLUB_KARSIYAKA': { clubId: 'CLUB_KARSIYAKA', teams: [1022, 1118] },
  'CLUB_ISTANBULBBSK': { clubId: 'CLUB_ISTANBULBBSK', teams: [1018] },
  'CLUB_MERINOS': { clubId: 'CLUB_MERINOS', teams: [1031, 1205] },
  'CLUB_PTT': { clubId: 'CLUB_PTT', teams: [1037, 1166] },
  'CLUB_YESILYURT': { clubId: 'CLUB_YESILYURT', teams: [1020, 1059] },
  'CLUB_BURSA_BSB': { clubId: 'CLUB_BURSA_BSB', teams: [1136] }
};
